#!/usr/bin/env python3
# stamp-plugin-version.py — records the producing plugin version in TWO places, from ONE derivation:
#
#     1. <spec_dir>/kiro-plugin-version-<VERSION>.md   (a marker file — rides along in the PR file list)
#     2. spec.json's root-level "plugin_version" field  (machine-readable — a gate/skill can read it
#        without globbing a filename pattern)
#
# PURPOSE: make kiro (cc-sdd) plugin-version adoption visible at PULL-REQUEST level, AND queryable by
# tooling. A spec dir is dated and per-feature/per-bug (.kiro/specs/<category>/YYYY-MM-DD-<slug>/), and
# a PR almost always touches exactly one spec dir — so a version marker living next to that spec's
# spec.json rides along in the PR. A reviewer can see from the PR file list which plugin version
# produced the work (who is on the latest vs an older one) without opening anything; a script (e.g.
# `kiro-gate.mjs`, a future CI check, or `validate-impl`'s staleness check) can read spec.json's field
# directly instead of parsing a filename. The version is derived exactly once (`plugin_version()`
# below) and used for both writes — never hardcode a version string anywhere else in a template; a
# hardcoded value in a template is correct only until the next plugin release, then silently wrong.
#
# WHY A SKILL SCRIPT, NOT A HOOK: the calling skill already knows the exact spec dir, so it passes it
# in — no global always-on hook firing on every session / every repo, and no "guess the active spec"
# heuristic. It runs ONLY when a kiro skill runs, and only against the spec that skill owns.
#
# NO CHURN: it writes ONLY when the correct-version marker is missing or a stale-version marker is
# present (then prunes the old one and writes the new). Steady state is a pure no-op, so re-running it
# (e.g. impl re-stamping a spec created earlier on an older version) never dirties git unless the
# version actually changed. The marker holds NO timestamp for this reason — it changes only when the
# plugin version changes, which is exactly the signal to surface in a PR.
#
# SAFETY: always exit 0 (a version stamp must never block or fail a skill). Fail silent. If the
# plugin version cannot be resolved (e.g. a non-plugin distribution with no plugin.json), write
# NOTHING — never stamp an "unknown" marker.
#
# Usage:  python3 stamp-plugin-version.py <spec_dir>
# Pure stdlib (os, sys, json) — runs on any vanilla macOS python3.
import os
import sys
import json

PREFIX = "kiro-plugin-version-"


def plugin_version():
    """Best-effort kiro plugin version, or None. Prefer the runtime-exported ${CLAUDE_PLUGIN_ROOT};
    else walk up from this script's own bundled location (plugin/skills/<x>/scripts/) to the plugin
    manifest."""
    candidates = []
    root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if root:
        candidates.append(os.path.join(root, ".claude-plugin", "plugin.json"))
    try:
        d = os.path.dirname(os.path.realpath(__file__))
        for _ in range(8):
            candidates.append(os.path.join(d, ".claude-plugin", "plugin.json"))
            parent = os.path.dirname(d)
            if parent == d:
                break
            d = parent
    except Exception:
        pass
    for manifest in candidates:
        try:
            with open(manifest, encoding="utf-8") as fh:
                v = json.load(fh).get("version")
            if isinstance(v, str) and v.strip():
                return v.strip()
        except Exception:
            continue
    return None


def marker_body(version):
    return (
        "# kiro (cc-sdd) plugin — version marker\n\n"
        "version: " + version + "\n\n"
        "Auto-generated by the kiro plugin whenever it works this spec. The filename encodes the "
        "plugin version in use so that pull requests surface which plugin version produced the work "
        "(to track who is on the latest plugin vs an older one). Managed by the version-stamp skill "
        "step — do not edit or delete by hand.\n"
    )


def stamp(spec_dir):
    """Ensure exactly one current-version marker exists in spec_dir. No-op if already correct;
    returns without writing if the dir is missing or the version is unknown."""
    if not spec_dir or not isinstance(spec_dir, str):
        return
    d = os.path.abspath(spec_dir)
    if not os.path.isdir(d):  # the calling skill has already created the spec dir
        return
    version = plugin_version()
    if not version:
        return  # never write an "unknown" marker

    target_name = PREFIX + version + ".md"
    target = os.path.join(d, target_name)

    try:
        existing = [f for f in os.listdir(d) if f.startswith(PREFIX) and f.endswith(".md")]
    except OSError:
        existing = []

    # Steady state for the MARKER FILE: the only marker present is the correct one → no marker
    # rewrite needed. spec.json is a SEPARATE target with its own no-op check inside
    # stamp_spec_json — always attempt it, even when the marker file needed no change. Every spec
    # that predates this field (i.e. every spec on disk right now) already has a correctly-named
    # marker from an earlier run, and would silently never get spec.json backfilled if this call
    # sat behind the marker's own early-return.
    marker_is_current = existing == [target_name] and os.path.isfile(target)

    if not marker_is_current:
        # Prune any stale-version markers so exactly one remains → a PR shows old-deleted + new-added.
        for f in existing:
            if f != target_name:
                try:
                    os.remove(os.path.join(d, f))
                except OSError:
                    pass
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(marker_body(version))

    stamp_spec_json(d, version)


def stamp_spec_json(spec_dir, version):
    """Set/refresh the root-level "plugin_version" field in spec_dir/spec.json to the same derived
    version the marker file uses. No-op if spec.json is missing, unreadable, or already correct — a
    version stamp must never corrupt or clobber a spec.json a skill is mid-write on."""
    path = os.path.join(spec_dir, "spec.json")
    if not os.path.isfile(path):
        return  # nothing to stamp yet — the calling skill hasn't written spec.json
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception:
        return  # malformed/mid-write spec.json — never touch it
    if not isinstance(data, dict):
        return
    if data.get("plugin_version") == version:
        return  # already correct — no-op, no git churn
    data["plugin_version"] = version
    try:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
    except Exception:
        pass  # fail silent, same contract as the marker-file write


def main():
    try:
        stamp(sys.argv[1] if len(sys.argv) > 1 else "")
    except Exception:
        # Fail silent — a version stamp must never disrupt a skill.
        pass
    sys.exit(0)


if __name__ == "__main__":
    main()
